version: 1
disable_existing_loggers: false
#objects:
#  queue:
#    class: queue.Queue
#    maxsize: 1000
formatters:
  simple:
    format: '[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  json:
    (): custom_loggers.mylogger.MyJSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
handlers:
  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  file_json:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: json
    filename: ./logs/my_app.log.jsonl
    maxBytes: 10000
    backupCount: 3
#  queue_listener:
#    class: src.custom_loggers.queue_handler.QueueListenerHandler
#    handlers:
#      - cfg://handlers.console
#      - cfg://handlers.file
#    queue: cfg://objects.queue
#  queue_handler:
#    class: logging.handlers.QueueHandler
#    handlers:
#      - cfg://handlers.stderr
#      - cfg://handlers.file_json
#    queue: cfg://objects.queue
#    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
    - stderr
    - file_json
